services:
  postgres:
    image: 'postgres:15.13'
    container_name: "postgres"
    restart: unless-stopped
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user_service_user" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    environment:
      - 'POSTGRES_DB=user_service_prod'
      - 'POSTGRES_PASSWORD=${USER_SERVICE_DB_PASSWORD}'
      - 'POSTGRES_USER=user_service_user'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
volumes:
  pgdata:
networks:
  backend:
    driver: bridge
