services:
  postgres:
    image: 'postgres:15.13'
    container_name: "postgres"
    restart: unless-stopped
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user_service_user", "-d", "user_service_prod" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    environment:
      - 'POSTGRES_DB=user_service_prod'
      - 'POSTGRES_PASSWORD=${USER_SERVICE_DB_PASSWORD}'
      - 'POSTGRES_USER=user_service_user'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: 'redis:8.0'
    container_name: "redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    command: ["redis-server", "--requirepass", "${USER_SERVICE_REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data
    networks:
      - backend

volumes:
  pgdata:
  redisdata:

networks:
  backend:
    driver: bridge
