spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_prod
    username: user_service_user
    password: ${USER_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: prod-redis-host
      port: 6379

logging:
  level:
    root: WARN
